### ISSUE TITLE
BoilerBooks v2 TODO

### ISSUE THREAD

**Issue by avaidyam** [PurdueIEEE/boilerbooks#53]
The following are the remaining items to be completed before BoilerBooks v2 is operational:
- [x] Changelog support
- [x] Use SSE to communicate realtime data changes to clients.
- [x] Finish `*.search()` APIs.
- [ ] `Resource` usage for certificates and receipts.

Future things that aren't so important:
- [ ] `errors.json` catalog with mapping `{ code => msg }` for both client and server.
- [ ] `User.deleted` and `User.email_notify` flags required.
- [ ] Linked balance transfers: i.e. `purchase.link == income.link`, we should interpret this as a "transfer" and not two separate entities.
- [ ] Parenthetical grouping and OR operator for `*.search()` queries.

For searching: 
```
?fields=a,b,c,max:d,count:b
	- element: [<operator>:]<name>[, ...]
	- operators: min, max, avg, sum, count
?filter=a:is:55|b:like:hello&c:lt:39
	- element: <name>:<operator>:<compare>[conjunct ...]
	- operators: is, not, lt/lte, gt/gte
	- conjunctions: & and, | or, % like
```

**Comment by avaidyam** [comment]
Possible reworking of `Rights` proposed. Not sure what to do about it though...

**Comment by rakoskr6** [comment]
Will close this for now since "v2" is abandoned
